BEGIN;
DROP TABLE "articletrack_comment";
DROP TABLE "articletrack_ticket";
ALTER TABLE "articletrack_article_journals" DROP CONSTRAINT "article_id_refs_id_88255549";
ALTER TABLE "articletrack_checkin" DROP CONSTRAINT "article_id_refs_id_1e1cac44";
DROP TABLE "articletrack_article";
DROP TABLE "articletrack_article_journals";
DROP TABLE "articletrack_checkinworkflowlog";
ALTER TABLE "articletrack_notice" DROP CONSTRAINT "checkin_id_refs_id_5dd690e9";
DROP TABLE "articletrack_checkin";
DROP TABLE "articletrack_notice";
ALTER TABLE "articletrack_team_member" DROP CONSTRAINT "team_id_refs_id_4fdee4e9";
DROP TABLE "articletrack_team";
DROP TABLE "articletrack_team_member";
COMMIT;
