# Generated by Django 5.1.15 on 2026-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('begin_at', models.DateTimeField(verbose_name='Begin at')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='End at')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_blocking_users', models.BooleanField(db_index=True, default=False, help_text='once it is checked, it will set up the other events to false', verbose_name='is blocking users')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('event_report', models.TextField(blank=True, verbose_name='Report')),
            ],
            options={
                'ordering': ['begin_at', 'title'],
            },
        ),
    ]
