# Generated by Django 5.1.15 on 2026-03-03 14:45

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journalmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Role Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EditorialBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journalmanager.issue')),
            ],
        ),
        migrations.CreateModel(
            name='EditorialMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('institution', models.CharField(default='', max_length=256, verbose_name='institution')),
                ('link_cv', models.URLField(blank=True, null=True, verbose_name='Link CV')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=256, null=True, verbose_name='State')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('research_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='ResearcherID')),
                ('orcid', models.CharField(blank=True, max_length=256, null=True, verbose_name='ORCID')),
                ('order', models.IntegerField(default=1, verbose_name='board order')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorialmanager.editorialboard')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorialmanager.roletype')),
            ],
            options={
                'ordering': ('board', 'order', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='RoleTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Role Name')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalmanager.language')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='editorialmanager.roletype')),
            ],
            options={
                'unique_together': {('role', 'language')},
            },
        ),
    ]
